name: Build and Deploy

on:
  push:
    branches:
      - main  # Replace 'main' with your primary branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Zola
        run: |
          curl -s -L https://github.com/getzola/zola/releases/latest/download/zola-x86_64-unknown-linux-gnu.tar.gz | sudo tar xvzf - -C /usr/local/bin

      - name: Build site with Zola
        run: zola build  # Modify if your build command is different

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public  # Modify if your Zola output directory is different
          publish_branch: gh-pages
          cname: example.com  # Replace with your custom domain, if applicable
          force_orphan: true
